### ISSUE TITLE
Supporting dynamic switching between databases

### ISSUE THREAD

**Issue by ocha** [ankane/multiverse#1]
I was considering using this library in my project and I am wondering if having support for dynamic database switching similar to apartments gem is out of scope for this project.

**Comment by mykola-kyryk** [comment]
Dynamic switching is especially interesting if you have one database but want to use Read Replica.
So in the controller you would setup to use Read Replica for `index` and `show`, and Main DB for `create` and `update`.

**Comment by ankane** [comment]
Hey @ocha, the Apartment gem was designed for horizontal sharding (same table in multiple DBs but different data), whereas this is designed for vertical sharding (some tables are in one DB, others are in other, but not in both).

@mykola-kyryk for replicas, check out [Distribute Reads](https://github.com/ankane/distribute_reads).
