### ISSUE TITLE
allow engine migration path

### ISSUE THREAD

**Issue by patleb** [ankane/multiverse#11]
Hi, just to let you know that it's currently not possible to use migrations within engines, but could be if this [line](https://github.com/ankane/multiverse/blob/master/lib/multiverse/railtie.rb#L30) is changed to:

```ruby
ActiveRecord::Tasks::DatabaseTasks.migrations_paths.map!{ |path| path.sub 'db/migrate', Multiverse.migrate_path }
```
or something similar.

**Comment by ankane** [comment]
Thanks @patleb, can you share a good engine to test this with?

**Comment by patleb** [comment]
The only engines I know of that use this pattern are the one I develop or applications built around common engines (ex.: an Admin + an API that would use the same models/migrations extracted within a Core engine). I've used your gem recently to allow a client application to use a local database as a cheap storage to consult archived dumps. Part of the integration is [here](https://github.com/patleb/ext_plugins/tree/master/ext_multiverse) and one of the engines using it is [here](https://github.com/patleb/ext_plugins/tree/master/ext_globals).

**Comment by phildionne** [comment]
Also, one step towards making this work most likely implies something like:

```ruby
# config/initializers/blorgh.rb
ActiveRecord::Tasks::DatabaseTasks.migrations_paths << File.expand_path(Multiverse.migrate_path, Blorgh::Engine.config.root)
```

**Comment by patleb** [comment]
@phildionne, @ankane, the article explaining how to add migrations to engines is [here](https://content.pivotal.io/blog/leave-your-migrations-in-your-rails-engines).

@ankane, for an engine named `MyEngine` with the file `lib/my_engine/engine.rb`:
```ruby
module MyEngine
  class Engine < ::Rails::Engine
    initializer 'my_engine.append_migrations' do |app|
      unless app.root.to_s.match(root.to_s)
        config.paths["db/migrate"].expanded.each do |expanded_path|
          app.config.paths["db/migrate"] << expanded_path
        end
      end
    end
  end
end
```
you would get as migration paths for a second db named `other_db`:
- my_app/db/other_db/migrate
- my_engine/db/other_db/migrate

The problem with the current implementation is that you overwrite by assigning a new array instead of transforming the current one (which could include more than one path).

**Comment by ankane** [comment]
Agree that's problem we'll likely need to address, but from the error, it looks like an issue with the rake task.

**Comment by patleb** [comment]
Yep, that's why I mentionned the problematic [line](https://github.com/ankane/multiverse/blob/master/lib/multiverse/railtie.rb#L30) previously. Feel free to address the issue or not, I was just mentionning the potential problem (which happens only if migrations are in engines) in case other people need a solution.

**Comment by ankane** [comment]
I'm concerned about the suggested approach because it'll break if someone adds a path that doesn't have `db/migrate` in it (and incorrectly include a directory that shouldn't be included).

**Comment by patleb** [comment]
Agreed, this would be more flexible:

```ruby
db_migrate_path = Rails.application.config.paths["db/migrate"].to_ary.first
ActiveRecord::Tasks::DatabaseTasks.migrations_paths.map!{ |path| path.sub db_migrate_path, Multiverse.migrate_path }
```

**Comment by ankane** [comment]
I'm not sure that solves it. The app can set a path that doesn't match the engine path at all (like `foo`).

**Comment by ankane** [comment]
My suggestion would be to update the engine code that changes `config.paths["db/migrate"]` to correctly change it when `Multiverse.db` is set.

**Comment by patleb** [comment]
It would mean that you have to change every single engine to make it work with Multiverse instead of making Multiverse work with any architecture. Alternatively, you could go with:

```ruby
paths = ([Rails.application.config] + Rails::Engine.subclasses.map(&:config)).map do |engine|
  db_migrate_path = engine.paths['db/migrate'].to_ary.first
  [engine.root.join(db_migrate_path).to_s, db_migrate_path]
end.to_h
ActiveRecord::Tasks::DatabaseTasks.migrations_paths.map! do |path|
  path.sub paths[path], Multiverse.migrate_path
end
```
that would allow custom path set in engines and the application.

**Comment by ankane** [comment]
I think that code would make all paths the same (`Multiverse.migrate_path`). Anyways, I appreciate the suggestion and discussion, but don't want to introduce the complexity at this time.
