### ISSUE TITLE
dbconsole

### ISSUE THREAD

**Issue by jjb** [ankane/multiverse#15]
Thanks for multiverse - I just started using it and it's been great so far!

Do you think it would be useful/possible to support this?

`DB=catalog rails dbconsole`

**Comment by ankane** [comment]
Hey @jjb, I think it could be useful. Happy to accept a PR for it. Will need to add it to the test suite to make sure it works across all supported versions of Rails.

**Comment by jjb** [comment]
by default `rails dbconsole` starts the console with the main app database selected. foo_development. to switch to my other multiverse-enabled database, i have to do (in postgres) `\c catalog_development`.

**Comment by ankane** [comment]
Cleaning up issues. Since Rails 6 supports multiple databases :tada:, I don't plan to add any more significant features.
