### ISSUE TITLE
migrations run against wrong database

### ISSUE THREAD

**Issue by jjb** [ankane/multiverse#16]
I have a migration in db/foo/migrate that ended up being run against the main database in my staging environment.

In my development environment things worked as expected.

I'm going to do my own research but wanted to get this ticket in because it seems like it should be impossible for for this to happen. Any ideas?

**Comment by ankane** [comment]
Hey @jjb, there shouldn't be any difference between development and staging. I'd make sure your `database.yml` is correct for staging.

**Comment by edmondchui** [comment]
@jjb Did you use the following command

```bash
DB=foo bundle exec rake db:migrate
```

**Comment by jjb** [comment]
@edmondchui 

yes, i did. but even if i didn't, there should be no possible way for multiverse to mistakenly act on the wrong db. unless the `foo` config is pointing at the main db.

i can't think of how i would have had my multiverse-using code live, but not the config.

and even if that were the case, i assume that multiverse will blow up in such a scenario and not fall back to using the main db.

anyway, i don't mean to sound overly scary, it still very well could have been some sort of overlapping config scenario on my end. i'll explore more.

**Comment by ankane** [comment]
Closing stale issues. Please follow up if you find anything.
