### ISSUE TITLE
generate model can't auto generate  migration

### ISSUE THREAD

**Issue by wuyuedefeng** [ankane/multiverse#19]
![image](https://user-images.githubusercontent.com/7812631/44255286-18a2f080-a238-11e8-9a97-762bf860d777.png)

**Comment by ankane** [comment]
Hey @wuyuedefeng, what version of Rails and Multiverse are you on?

Also, try restarting Spring (`bin/spring stop`) to see if that fixes it.

**Comment by wuyuedefeng** [comment]
not solved. 
I used `ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]`
`Rails 5.2.1`
api mode

**Comment by ankane** [comment]
Thanks, able to reproduce and isolate down to [this line](https://github.com/ankane/multiverse/blob/34a1deebfc62ae766b276963b31fed366345d859/lib/multiverse/railtie.rb#L14), but not sure why it only happens in API mode.

**Comment by ankane** [comment]
Should be fixed on master. Thanks for reporting 👍
