### ISSUE TITLE
[Heroku] migrate command not picking the right database when DATABASE_URL is set

### ISSUE THREAD

**Issue by EdgarOrtegaRamirez** [ankane/multiverse#20]
Hello! First of all, thanks for this amazing lib, It is really helpful.

I've made a deployment to a Heroku app which has set the `DATABASE_URL` and the additional `CATALOG_DATABASE_URL`, but when migrating migrations are run on the main database and the catalog db is untouched.

Do you know if this is a known issue?

**Comment by ankane** [comment]
Hey @EdgarOrtegaRamirez, a similar issue was reported in #16, but haven't been able to reproduce. A few questions:

1. Does it work in development?
2. What version of Rails and Multiverse are you on? (make sure it's the latest Multiverse - 0.2.1)
3. Are migrations for the catalog database in `db/catalog/migrate`?
4. Do the migrations just not run, or do they run on the main database instead?
5. What does your `config/database.yml` look like?

**Comment by ankane** [comment]
The problem was the `url` indentation was off, so it wasn't affecting your `catalog_production` config.

**Comment by EdgarOrtegaRamirez** [comment]
I'm pretty sure that was a bad paste, sorry.

**Comment by EdgarOrtegaRamirez** [comment]
Was able to reproduce this again but on the CodeShip CI, `DATABASE_URL` was set in the configuration, I removed it and then it picked the right database configuration.

**Comment by EdgarOrtegaRamirez** [comment]
> When duplicate connection information is provided the environment variable will take precedence:
from: https://edgeguides.rubyonrails.org/configuring.html#connection-preference

This seems like a known issue...

**Comment by ankane** [comment]
Config is merged with `ENV["DATABASE_URL"]` if you don't have a `url` key for that environment. That's just how it's designed in Rails.
