### ISSUE TITLE
Preparing the test environment required for RSpec

### ISSUE THREAD

**Issue by bendelonlee** [ankane/multiverse#26]
I needed to run `$ DB=catalogue rails db:test:prepare`, which I don't need to run when setting up a standard database. Consider adding this to documentation.

Thanks for this useful gem!!

**Comment by ankane** [comment]
Thanks for reporting back. I believe you would only need to run this if you have a fresh database where you either haven't loaded the schema or migrated. Was that the case?

**Comment by bendelonlee** [comment]
It needed to be done after migrating. Here's an interaction pattern from this morning (Rails version 5.1.6).
```
=> (master)$ rails g multiverse:db catalog
      create  app/models/catalog_record.rb
      append  config/database.yml
      create  db/catalog/migrate
=> (master)$ DB=catalog rails db:create
Created database 'catalog_development'
Created database 'catalog_test'
=> (master)$ DB=catalog rails g model Product name:string price:integer
      invoke  active_record
      create    db/catalog/migrate/20190115173844_create_products.rb
      create    app/models/product.rb
      invoke    rspec
      create      spec/models/product_spec.rb
      invoke      factory_bot
      create        spec/factories/products.rb
=> (master)$ DB=catalog rails db:migrate
== 20190115173844 CreateProducts: migrating ===================================
-- create_table(:products)
   -> 0.0059s
== 20190115173844 CreateProducts: migrated (0.0060s) ==========================

=> (master)$ rspec spec/models/product_spec.rb
F

Failures:

  1) Product can create without errors
     Failure/Error: item = Product.create(name: "candle", price: 0)

     ActiveRecord::StatementInvalid:

       PG::UndefinedTable: ERROR:  relation "products" does not exist...
       
 => (master)$ DB=catalog rails db:test:prepare
 => (master)$ rspec spec/models/product_spec.rb
 .

 Finished in 0.03138 seconds (files took 2.39 seconds to load)
 1 example, 0 failures
```
After this, I generated a second model, migrated, got the same undefined table error, ran db:test:prepare again, which got rid of that error. I then rolled back the database. This didn't cause the test to fail. After I ran db:test:prepare, the test failed as expected. It seems it needs to run after every migration when using RSpec.

I did the same in separate project directory using Minitest and db:test:prepare wasn't needed.

**Comment by ankane** [comment]
Thanks, was able to reproduce. Updated docs.
