### ISSUE TITLE
Is `on_worker_boot` still required in Rails 5.2?

### ISSUE THREAD

**Issue by lleger** [ankane/multiverse#29]
The [README](https://github.com/ankane/multiverse/tree/a78a1832243026fef4c5d51937b5ab36b8d28c7c#web-servers) says:

> For web servers that fork, be sure to reconnect after forking (just like you do with ActiveRecord::Base)

But this is no longer required in Rails 5.2: https://github.com/rails/rails/pull/31241

Does this still apply to Multiverse or can it be dropped if using Rails 5.2+?

**Comment by ankane** [comment]
Hey @lleger, from the PR, that looks to be the case. Updated the readme. Thanks!
