### ISSUE TITLE
Could not dump table because of undefined method `column_spec_for_primary_key`

### ISSUE THREAD

**Issue by mklemme** [ankane/multiverse#7]
Just added the gem to a [rails-template](https://github.com/mklemme/rails-template/pull/24) I'm working on and the schema files got borked. 

Here's the diff for the pr:

https://github.com/mklemme/rails-template/pull/24/files#diff-1acd2e7e27a227829d5d14a91c863bb6

```ruby
# schema.rb
ActiveRecord::Schema.define(version: 2018_02_01_050311) do

# Could not dump table "users" because of following NoMethodError
#   undefined method `column_spec_for_primary_key' for #<ActiveRecord::SchemaDumper:0x00007f8f494322d8>

# ... cont

end
```

I used [devise](https://github.com/mklemme/rails-template/blob/master/db/migrate/20180121202039_devise_create_users.rb) for users and the other tables are custom.

Ruby 2.4.2
Rails 5.2.0.beta2

<img width="737" alt="screen shot 2018-02-14 at 11 14 53 pm" src="https://user-images.githubusercontent.com/1305776/36244983-87574ad0-11dd-11e8-9c67-ee94aabd4c96.png">
<img width="607" alt="screen shot 2018-02-14 at 11 14 46 pm" src="https://user-images.githubusercontent.com/1305776/36244985-8939026c-11dd-11e8-91c1-e1c197e5e481.png">

I haven't been able to find anything that could cause this. Any ideas?

**Comment by ankane** [comment]
Hey @mklemme, thanks for reporting 👍  Fixed on master.

**Comment by mklemme** [comment]
Confirming the update is working correctly now. I'll keep an eye out for the version bump. 

Thanks for the patch. This gem is really useful! 🎉
