### ISSUE TITLE
Question: Does it work for Rails 5/5.1 ?

### ISSUE THREAD

**Issue by tommyalvarez** [ankane/multiverse#9]
Just that. I need to implement multiple databases and i'm considering using either this gem or secondbase + thirdbase...
Please let me know!

**Comment by iaankrynauw** [comment]
Hey,

I've used it in rails 5.1 Capistrano deploy is my only issues so far.

**Comment by tommyalvarez** [comment]
@iaankrynauw great, closing issue then thx!
